MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-101"
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
  ROI_KEYPOINT_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "KeypointRCNNFeatureExtractor"
    PREDICTOR: "KeypointRCNNPredictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 56
    SHARE_BOX_FEATURE_EXTRACTOR: False
  MEDPOSE:
    FEATURE_ENLARGER: "KeypointRCNNFeatureEnlarger"
    HEATMAP_UPSCALE: 2
    STACK_LAYERS: 4
    WINDOW_SIZE: 3
    ROI_MAP_DIM: 6
    MODEL_DIM: 612
    NUM_KEYPOINTS: 17
  KEYPOINT_ON: True
  MEDPOSE_ON: False # using our architecture head (baseline or otherwise) instead of maskrcnn-benchmark
  MEDPOSE_ABLATION: False # setting this to True uses baseline model
DATASETS:
  TRAIN: ("posetrack_train",)
  TEST: ("posetrack_val",)
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 0
SOLVER:
  BASE_LR: 0.005
  WEIGHT_DECAY: 0.0001
  STEPS: (240000, 320000)
  MAX_ITER: 720000
  CHECKPOINT_PERIOD: 500
OUTPUT_DIR: "/scratch/users/kamilali/medpose-model-data/models_kprcnn_baseline_res101_coco_posttrained"
NUM_GPUS: 2
POSETRACK_EVAL: True
